### ISSUE TITLE
JS Import Bug/Typo in Polymer 3 @vaadin/vaadin-combo-box

### ISSUE THREAD

**Issue by paulreimer** [vaadin/vaadin-combo-box#690]
### Description
The follow patch seems to be needed for npm version of this package: (not sure where that codebase lives otherwise I could have made a PR)
```
diff -u -ar node_modules/@vaadin/vaadin-combo-box/theme/material/vaadin-combo-box-item-styles.js /tmp/@vaadin/vaadin-combo-box/theme/material/vaadin-combo-box-item-styles.js
--- node_modules/@vaadin/vaadin-combo-box/theme/material/vaadin-combo-box-item-styles.js	1985-10-26 01:15:00.000000000 -0700
+++ /tmp/@vaadin/vaadin-combo-box/theme/material/vaadin-combo-box-item-styles.js	2018-07-26 09:10:18.000000000 -0700
@@ -1,7 +1,7 @@
 import '@vaadin/vaadin-material-styles/color.js';
 import '@vaadin/vaadin-material-styles/font-icons.js';
 import '@vaadin/vaadin-material-styles/typography.js';
-import '@vaadin/vaadin-item/theme/material/vaadin-item.js';
+import '@vaadin/vaadin-item/theme/material/vaadin-item-styles.js';
 const $_documentContainer = document.createElement('div');
 $_documentContainer.setAttribute('style', 'display: none;');
 
diff -u -ar node_modules/@vaadin/vaadin-combo-box/theme/material/vaadin-combo-box-styles.js /tmp/@vaadin/vaadin-combo-box/theme/material/vaadin-combo-box-styles.js
--- node_modules/@vaadin/vaadin-combo-box/theme/material/vaadin-combo-box-styles.js	1985-10-26 01:15:00.000000000 -0700
+++ /tmp/@vaadin/vaadin-combo-box/theme/material/vaadin-combo-box-styles.js	2018-07-26 09:10:18.000000000 -0700
@@ -1,6 +1,6 @@
 import './vaadin-combo-box-dropdown-styles.js';
 import './vaadin-combo-box-item-styles.js';
-import '@vaadin/vaadin-text-field/theme/material/vaadin-text-field.js';
+import '@vaadin/vaadin-text-field/theme/material/vaadin-text-field-styles.js';
 import '@vaadin/vaadin-material-styles/color.js';
 import '@vaadin/vaadin-material-styles/font-icons.js';
 import '@vaadin/vaadin-material-styles/mixins/field-button.js';
```

Or, the files need to be renamed, but either way there is a mismatch between the name of the file have `-styles.js` and the `import` does not match that.

### Expected outcome
Having e.g. the following import in application code:
```
import "@vaadin/vaadin-combo-box/theme/material/vaadin-combo-box-styles.js";
import "@vaadin/vaadin-combo-box/vaadin-combo-box.js";
```
`polymer build` should complete without errors.

### Actual outcome
From a polymer 3 project build:
```
$ yarn run build
$ polymer build
info: [cli.command.build]    Clearing build/ directory...
error: [cli.main]   Promise rejection: Error: Could not load file://webcomponents/node_modules/%40vaadin/vaadin-combo-box/theme/material/%40vaadin/vaadin-item/theme/material/vaadin-item.js (imported by file://webcomponents/node_modules/%40vaadin/vaadin-combo-box/theme/material/vaadin-combo-box-item-styles.js): ENOENT: no such file or directory, open 'file://webcomponents/node_modules/%40vaadin/vaadin-combo-box/theme/material/%40vaadin/vaadin-item/theme/material/vaadin-item.js'
error: [cli.main]   Error: Could not load file://webcomponents/node_modules/%40vaadin/vaadin-combo-box/theme/material/%40vaadin/vaadin-item/theme/material/vaadin-item.js (imported by file://webcomponents/node_modules/%40vaadin/vaadin-combo-box/theme/material/vaadin-combo-box-item-styles.js): ENOENT: no such file or directory, open 'file://webcomponents/node_modules/%40vaadin/vaadin-combo-box/theme/material/%40vaadin/vaadin-item/theme/material/vaadin-item.js'
    at webcomponents/node_modules/rollup/dist/rollup.js:20561:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to reproduce
- Be using Polymer3 / LitElement
- `yarn add @vaadin/vaadin-combo-box`
- ```
import "@vaadin/vaadin-combo-box/theme/material/vaadin-combo-box-styles.js";
import "@vaadin/vaadin-combo-box/vaadin-combo-box.js";
```

**Comment by web-padawan** [comment]
Hi, the Material themed component should be loaded like this:
```js
import "@vaadin/vaadin-combo-box/theme/material/vaadin-combo-box.js";
```

This is the expected way of using it. Note that the Vaadin components use Lumo theme by default, and the `@vaadin/vaadin-combo-box/vaadin-combo-box.js` refers to the component with Lumo, so you should not load it separately when using Material themed version. Same applies to all our components.

**Comment by paulreimer** [comment]
That file does not exist for me in `"@vaadin/vaadin-combo-box": "^4.1.0-beta1",`? I still see the `vaadin-combo-box.html` HTML element file:
```
cat theme/material/vaadin-combo-box.html
<script type="module" src="./vaadin-combo-box-styles.js"></script>
<script type="module" src="../../src/vaadin-combo-box.js"></script>
```

So I turned that into the JS lines above when importing from within a JS module. And then I got the error above.

**Comment by web-padawan** [comment]
Thank you, now confirmed. It appears that some files are not converted properly for Material theme 😞
Thanks for pointing out. We will have to publish `beta2` asap.

**Comment by web-padawan** [comment]
I hope we will fix this and publish new versions tomorrow.  Apologies for the inconvenience, in the meanwhile you can temporarily downgrade to `pre` versions and pin them, until we release proper betas. 

These `pre` do not contain Material styles yet, but they at least work and should not cause any issues to your app. See working example: https://github.com/web-padawan/polymer3-webpack-starter/blob/master/package.json#L19

**Comment by web-padawan** [comment]
Fixed the imports in da30d07

@paulreimer we will close the issue and inform you once beta2 is published.

And, just to clarify (as you was not sure about where the codebase lives): we currently convert components using `polymer-modulizer` from Polymer 2 version and only publish to npm, but we do not push those to GitHub since the Polymer 2 versions use the same versions.
See also https://github.com/vaadin/vaadin-core/blob/p3-preview/DEVELOPMENT.md#polymer-3-contributing

**Comment by paulreimer** [comment]
Yup, 4.1.0-beta2 works for me with the recommended approach. Thanks!
