### ISSUE TITLE
Test failing in iOS 9.3 in Travis and simulator

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-combo-box#801]
The following test started to be flaky after 395e706

```
iOS Simulator iphone 9.3 ✖ test/lazy-loading.html » lazy loading » combo-box-light » dataProvider » should be invoked with size set
  expected dataProvider to have been called exactly once, but it was called twice
    dataProvider({ filter: "", page: 0, pageSize: 50 }, function callback() {}) at http://localhost:8081/components/@vaadin/[secure]/src/[secure]-data-provider-mixin.js:83:34
    dataProvider({ filter: "", page: 1, pageSize: 50 }, function callback() {}) at http://localhost:8081/components/@vaadin/[secure]/src/[secure]-data-provider-mixin.js:83:34
        dataProvider({ filter: "", page: 0, pageSize: 50 }, function callback() {}) at http://localhost:8081/components/ at vaadin/[secure]/src/[secure]-data-provider-mixin.js:83:34
        dataProvider({ filter: "", page: 1, pageSize: 50 }, function callback() {}) at http://localhost:8081/components/ at vaadin/[secure]/src/[secure]-data-provider-mixin.js:83:34
                                   <unknown> at   AssertionError at /components/chai/chai.js:5270:0
                                   <unknown> at           assert at /components/chai/chai.js:265:0
                                   <unknown> at        <unknown> at /components/sinon-chai/lib/sinon-chai.js:91:0
                                   <unknown> at      addProperty at /components/chai/chai.js:3961:0
                                   <unknown> at        <unknown> at lazy-loading.html:146:0
```

**Comment by Haprog** [comment]
These are also related and flaky in Travis

```
iOS Simulator iphone 11.3 ✖ test/lazy-loading.html » lazy loading » combo-box
  » dataProvider » when open » should not request on value change
  AssertionError: expected dataProvider to not have been called

iOS Simulator iphone 11.3 ✖ test/lazy-loading.html » lazy loading » combo-box-light
  » dataProvider » when open » should not request on value change
  AssertionError: expected dataProvider to not have been called

iOS Simulator iphone 9.3 ✖ test/lazy-loading.html » lazy loading » combo-box-light
  » dataProvider » when open » should not request on value change
```

**Comment by Haprog** [comment]
Still seems to be a problem in CI at least with these tests:
```
iOS Simulator iphone 11.3 ✖ test/lazy-loading.html » lazy loading » combo-box-light » dataProvider » when open » should not request on value change
iOS Simulator iphone 9.3 ✖ test/lazy-loading.html » lazy loading » combo-box-light » dataProvider » when open » should clear filter on value clear
iOS Simulator iphone 9.3 ✖ test/lazy-loading.html » lazy loading » combo-box-light » dataProvider » when open » should not request on value change
```

But I have not been able to reproduce these failures locally with iOS Simulator (tried with "iPhone 6 iOS 9.3", "iPhone 6 Plus iOS 9.3" and "iPhone 6 Plus iOS 11.3").

**Comment by Haprog** [comment]
Easiest way to reproduce this seems to be to actually run the tests in SauceLabs via WCT, but to make it as fast as possible you can run it locally `./node_modules/.bin/wct --env saucelabs` (with Sauce credentials set in env variables) and temporarily edit `wct.conf.js` so that it only runs the tests in `'iOS Simulator/iphone@9.3'` and edit `test-suites.js` so it only includes `window.VaadinComboBoxSuites = ['lazy-loading.html'];` and in `lazy-loading.html` use `describe.only` and `it.only` to only run a smaller portion of the tests.

Thought it seems that when running only the failing test or two, it's likely to pass, so the issue seems to be only in combination of running a bunch of these tests.

In this case it's reproducible at least when running only all the `dataProvider > when open` tests (for both `combo-box` and `combo-box-light`.

**Comment by Haprog** [comment]
Finally found an easy way to reproduce this issue even on Chrome.

It seems that this specific issue with the lazy-loading tests only occurs when the viewport height is 909 px or more. You can reproduce this in Chrome by zooming out the page a few steps (depending on your display resolution) or just using Chrome dev tools device toolbar with "Responsive" mode and setting the viewport height to 909 px or more (e.g. 1100 px to be sure).

Doing this makes also some other tests fail (not sure if those are now skipped on iOS, I will check and see if we can fix more tests).

The problem with iOS in SauceLabs (running via WCT) seems to be that it somehow runs the tests with a huge viewport size. I tested the viewport size used by it by running tests with:

```js
expect(document.documentElement.clientHeight).to.equal(0);
expect(window.innerHeight).to.equal(0);
```

which resulted in:

```
iOS Simulator iphone 9.3 ... expected 1485 to equal 0
iOS Simulator iphone 9.3 ... expected 1485 to equal 0
iOS Simulator iphone 11.3 ... expected 1469 to equal 0
iOS Simulator iphone 11.3 ... expected 1469 to equal 0
```

So the `iOS Simulator iphone 9.3` seems to run with a viewport height of 1485 px and `iOS Simulator iphone 11.3` with a viewport height of 1469 px.

With these lazy-loading tests that are expecting the data provider to be called specific amount of times that fails when it actually triggers the data provider second time to load the second page of data too (with this large viewport height) when pagesize is set to 50.
