### ISSUE TITLE
Bug when importing both text field and combo box

### ISSUE THREAD

**Issue by Kurren123** [vaadin/vaadin-combo-box#821]
When these two lines are at the top of my js file:

```JavaScript
import '@vaadin/vaadin-text-field/vaadin-text-field.js'
import '@vaadin/vaadin-combo-box/vaadin-combo-box.js'
```

I get the following error:
`Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-text-field" has already been used with this registry`.

I suspect the combo box isn't checking to see if the text field is already defined.

Full error is as follows:
```
vaadin-text-field.js:137 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-text-field" has already been used with this registry
    at Module../node_modules/@vaadin/vaadin-combo-box/node_modules/@vaadin/vaadin-text-field/src/vaadin-text-field.js (http://localhost:8081/main.js:18512:16)
    at __webpack_require__ (http://localhost:8081/main.js:20:30)
    at Module../node_modules/@vaadin/vaadin-combo-box/node_modules/@vaadin/vaadin-text-field/theme/lumo/vaadin-text-field.js (http://localhost:8081/main.js:18838:83)
    at __webpack_require__ (http://localhost:8081/main.js:20:30)
    at Module../node_modules/@vaadin/vaadin-combo-box/theme/lumo/vaadin-combo-box-styles.js (http://localhost:8081/main.js:21687:115)
    at __webpack_require__ (http://localhost:8081/main.js:20:30)
    at Module../node_modules/@vaadin/vaadin-combo-box/theme/lumo/vaadin-combo-box.js (http://localhost:8081/main.js:21724:85)
    at __webpack_require__ (http://localhost:8081/main.js:20:30)
    at Module../node_modules/@vaadin/vaadin-combo-box/vaadin-combo-box.js (http://localhost:8081/main.js:21743:89)
    at __webpack_require__ (http://localhost:8081/main.js:20:30)
```

Versions:
```
    "@vaadin/vaadin-combo-box": "^5.0.3",
    "@vaadin/vaadin-text-field": "^2.3.5",
```

OS: Windows 10
Browser: Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by web-padawan** [comment]
This is a duplicate dependency installation, which sometimes happens.

Please try doing the following:
```
rm -rf node_modules package-lock.json && npm i
```

If that doesn't help, also try the following:

```
npm dedupe
```

I'm closing this issue as there is nothing else we can do in the component to avoid that.
Please comment if you need any help.

**Comment by hibc** [comment]
Hey @web-padawan 
After I've updated vaddin-combo-box from ^4.2.8 to ^5.0.6, I'm getting the same error.
I've tried both solutions you provided, but still no luck. 
When I downgraded back to ^4.2.8, it works again.

**Comment by sdyalor** [comment]
> This is a duplicate dependency installation, which sometimes happens.
> 
> Please try doing the following:
> 
> ```
> rm -rf node_modules package-lock.json && npm i
> ```
> 
> If that doesn't help, also try the following:
> 
> ```
> npm dedupe
> ```
> 
> I'm closing this issue as there is nothing else we can do in the component to avoid that.
> Please comment if you need any help.

Worked!!! Ty
